# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c0d90f433cf68dd996d3b5ef746f5cbff35acda33ec7e3b3dc7ab056030882eea5b80cf9593e94e514da3c4c8b65b5e31f4d4a086c41f59afc0eb82fee878cb6

test:
  secret_key_base: 090ac7a53bd1eb8f670d5a3fb849ae6e07fc3df749e8ea113194aee12c744d44547633373ef4101f644cc8692cd8c946807f67d8f48a13d87317aa15616ed772

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
